/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.Arbol;
import java.io.IOException;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author joseg
 */
public class frm_recorridos extends javax.swing.JFrame {

    /**
     * Creates new form frm_recorridos
     */
    Arbol arbol = new Arbol();
    public frm_recorridos() {
        initComponents();

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_InOrden = new javax.swing.JButton();
        btn_PosOrden = new javax.swing.JButton();
        btn_PreOrden = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        brn_generar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Este programa genera automaticamente un millón de numeros en un arbol ");

        jLabel2.setText("y hace los tres recorridos de un arbol binario");

        jLabel3.setText("Recorrido InOrden");

        jLabel4.setText("Recorrido PosOrden");

        jLabel5.setText("Recorrido PreOrden");

        btn_InOrden.setText("INORDEN");
        btn_InOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InOrdenActionPerformed(evt);
            }
        });

        btn_PosOrden.setText("POSORDEN");
        btn_PosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PosOrdenActionPerformed(evt);
            }
        });

        btn_PreOrden.setText("PREORDEN");
        btn_PreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreOrdenActionPerformed(evt);
            }
        });

        jLabel6.setText("Generar Numeros");

        brn_generar.setText("GENERAR");
        brn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_InOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_PosOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_PreOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brn_generar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_InOrden)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_PosOrden)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_PreOrden)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PosOrdenActionPerformed
        try {
            // TODO add your handling code here:
            arbol.PosOrden();
            System.out.println("");
            System.out.println("RECORRIDO POSORDEN CORRECTAMENTE GENERADO");
            System.out.println("-----------------------------------------------------------------");
        } catch (IOException ex) {
            Logger.getLogger(frm_recorridos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_PosOrdenActionPerformed

    private void btn_PreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreOrdenActionPerformed
        try {
            // TODO add your handling code here:
            arbol.PreOrden();
            System.out.println("");
            System.out.println("RECORRIDO PREORDEN CORRECTAMENTE GENERADO");
            System.out.println("-----------------------------------------------------------------");
        } catch (IOException ex) {
            Logger.getLogger(frm_recorridos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_PreOrdenActionPerformed

    private void btn_InOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InOrdenActionPerformed
        try {
            // TODO add your handling code here:
            arbol.InOrden(arbol.raiz);
            System.out.println("");
            System.out.println("RECORRIDO INORDEN CORRECTAMENTE GENERADO");
            System.out.println("-----------------------------------------------------------------");
        } catch (IOException ex) {
            Logger.getLogger(frm_recorridos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_InOrdenActionPerformed

    private void brn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_generarActionPerformed
        // TODO add your handling code here:
        for (int i =0; i<1000000;i++)
        {
            int random = ThreadLocalRandom.current().nextInt(10000000+1);
            arbol.insertar(random);
        }
        System.out.println("NUMEROS GENERADOS CORRECTAMENTE");
        System.out.println("-----------------------------------------------------------------");
        
    }//GEN-LAST:event_brn_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_recorridos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_generar;
    private javax.swing.JButton btn_InOrden;
    private javax.swing.JButton btn_PosOrden;
    private javax.swing.JButton btn_PreOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
